version: '3.8'

services:
  newsboat:
    image: guzmansalv/newsboat-arch 
    container_name: newsboat
    volumes:
      - ./data/newsboat/:/root/.newsboat
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rss
    volumes:
      - ./data/newsboat/pgdata/:/var/lib/postgresql/data
    restart: always

# Ensure the following directories are created on the host:
# ./newsboat-config: To store the Newsboat configuration files
# ./newsboat-data: To store the Newsboat SQLite database

